/*
 * Copyright 2024-2026 Embabel Pty Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.entropy.database.mcp.tools;

import com.entropy.database.mcp.config.TestSecurityConfig;
import com.entropy.database.mcp.dialect.GenericDialect;
import com.entropy.database.mcp.exception.McpToolException;
import com.entropy.database.mcp.facade.RoutingDatabaseFacade;
import com.entropy.database.mcp.byok.DynamicDataSourceManager;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.core.env.Environment;

import javax.sql.DataSource;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Tests for administration MCP tools.
 *
 * Response format follows MCP/JSON-RPC 2.0 conventions:
 * - Success: data map (no wrapper)
 * - Error: {"error": {"code": "...", "message": "..."}}
 */
@SpringBootTest(properties = {
        "entropy.mcp.database.ddl.allowed=true",
        "entropy.mcp.gateway.enabled=false"
})
@Import(TestSecurityConfig.class)
class AdminToolsTest {

    @Autowired
    private OracleSessionTools oracleSessionTools;

    @Autowired
    private DatabaseHealthTools databaseHealthTools;

    @Autowired
    private RoutingDatabaseFacade routingFacade;

    @Autowired
    private DynamicDataSourceManager dataSourceManager;

    @Autowired
    private Environment environment;

    // ─── Setup ────────────────────────────────────────────────────────────

    @BeforeAll
    static void setUp(@Autowired DynamicDataSourceManager dataSourceManager) throws Exception {
        org.h2.Driver.load();
        org.h2.jdbcx.JdbcDataSource dataSource = new org.h2.jdbcx.JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:admintest;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false");
        dataSource.setUser("sa");
        dataSource.setPassword("");

        dataSourceManager.registerExisting("primary", dataSource, new GenericDialect());

        // Create audit_log table required by QueryAuditLoggerImpl
        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement()) {
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS audit_log (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tool VARCHAR(100) NOT NULL,
                    sql VARCHAR(2000),
                    rows INTEGER DEFAULT 0,
                    duration_ms BIGINT DEFAULT 0,
                    success INTEGER DEFAULT 1,
                    error VARCHAR(1000),
                    timestamp TIMESTAMP NOT NULL,
                    connection_key VARCHAR(200)
                )
                """);
        }
    }

    // ─── killSession validation tests ────────────────────────────────────────

    @Test
    void testKillSessionBlankSessionId() {
        assertThatThrownBy(() -> oracleSessionTools.killSession("", null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("sessionId cannot be blank");
    }

    @Test
    void testKillSessionNullSessionId() {
        assertThatThrownBy(() -> oracleSessionTools.killSession(null, null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("sessionId cannot be blank");
    }

    @Test
    void testKillSessionInvalidFormat() {
        assertThatThrownBy(() -> oracleSessionTools.killSession("123", null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("sessionId must be in format");
    }

    @Test
    void testKillSessionInvalidFormatLetters() {
        assertThatThrownBy(() -> oracleSessionTools.killSession("abc,def", null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("sessionId must be in format");
    }

    @Test
    void testKillSessionInvalidMode() {
        assertThatThrownBy(() -> oracleSessionTools.killSession("123,4567", "INVALID", "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("mode must be IMMEDIATE or POST_TRANSACTION");
    }

    @Test
    void testKillSessionValidFormat() {
        // H2 doesn't support ALTER SYSTEM, so killSessionSql returns null → KILL_SESSION_NOT_SUPPORTED
        assertThatThrownBy(() -> oracleSessionTools.killSession("123,4567", null, "primary"))
                .isInstanceOf(McpToolException.class);
    }

    @Test
    void testKillSessionPostTransactionMode() {
        assertThatThrownBy(() -> oracleSessionTools.killSession("123,4567", "POST_TRANSACTION", "primary"))
                .isInstanceOf(McpToolException.class);
    }

    @Test
    void testKillSessionLowerCaseMode() {
        // lowercase mode is normalized to IMMEDIATE internally, but H2 doesn't support it → error
        assertThatThrownBy(() -> oracleSessionTools.killSession("123,4567", "immediate", "primary"))
                .isInstanceOf(McpToolException.class);
    }

    // ─── P0: Diagnostic Tools ────────────────────────────────────────────────

    @Test
    void testListActiveSessions() {
        Map<String, Object> result = databaseHealthTools.listActiveSessions("primary");
        assertThat(result).containsKey("dialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    @Test
    void testShowLocks() {
        Map<String, Object> result = databaseHealthTools.showLocks("primary");
        assertThat(result).containsKey("dialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    @Test
    void testShowBlockingTree() {
        Map<String, Object> result = databaseHealthTools.showBlockingTree("primary");
        assertThat(result).containsKey("dialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    // ─── P1: Storage and Capacity Management ─────────────────────────────────

    @Test
    void testListTablespaces() {
        Map<String, Object> result = databaseHealthTools.listTablespaces("primary");
        assertThat(result).containsKey("dialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    @Test
    void testListDataFiles() {
        Map<String, Object> result = databaseHealthTools.listDataFiles("primary");
        assertThat(result).containsKey("dialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    @Test
    void testEstimateTableSizeIsUnsupportedWithoutASizeSource() {
        // GenericDialect has no data dictionary to read segment sizes from. It used to answer with a
        // constant size_mb=0 row, which is indistinguishable from "the table really is empty"; it now
        // declares the operation unsupported so the model cannot act on a fabricated number.
        assertThatThrownBy(() -> databaseHealthTools.estimateTableSize("MY_TABLE", null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("Dialect query execution failed");
    }

    @Test
    void testEstimateTableSizeBlankTableName() {
        assertThatThrownBy(() -> databaseHealthTools.estimateTableSize("", null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("tableName cannot be blank");
    }

    @Test
    void testEstimateTableSizeNullTableName() {
        assertThatThrownBy(() -> databaseHealthTools.estimateTableSize(null, null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("tableName cannot be blank");
    }

    // ─── P2: Object Health and Statistics ────────────────────────────────────

    @Test
    void testListInvalidObjects() {
        Map<String, Object> result = databaseHealthTools.listInvalidObjects(null, "primary");
        assertThat(result).containsKey("dialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    @Test
    void testGatherTableStats() {
        Map<String, Object> result = databaseHealthTools.gatherTableStats("MY_TABLE", null, "primary");
        assertThat(result).containsKey("tableName");
        assertThat(result.get("tableName")).isEqualTo("MY_TABLE");
        assertThat(result).containsKey("dialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    @Test
    void testGatherTableStatsBlankTableName() {
        assertThatThrownBy(() -> databaseHealthTools.gatherTableStats("", null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("tableName cannot be blank");
    }

    @Test
    void testGatherTableStatsNullTableName() {
        assertThatThrownBy(() -> databaseHealthTools.gatherTableStats(null, null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("tableName cannot be blank");
    }

    @Test
    void testShowIndexStatus() {
        Map<String, Object> result = databaseHealthTools.showIndexStatus(null, null, "primary");
        assertThat(result).containsKey("dialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    // ─── P3: Flashback and Undo Management ───────────────────────────────────

    @Test
    void testFlashbackQuery() {
        Map<String, Object> result = databaseHealthTools.flashbackQuery("MY_TABLE", "2024-01-01 00:00:00", null, "primary");
        assertThat(result).containsKey("tableName");
        assertThat(result.get("tableName")).isEqualTo("MY_TABLE");
        assertThat(result).containsKey("timestamp");
        assertThat(result.get("dialect")).isEqualTo("GenericDialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    @Test
    void testFlashbackQueryBlankTableName() {
        assertThatThrownBy(() -> databaseHealthTools.flashbackQuery("", "2024-01-01", null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("tableName cannot be blank");
    }

    @Test
    void testFlashbackQueryNullTableName() {
        assertThatThrownBy(() -> databaseHealthTools.flashbackQuery(null, "2024-01-01", null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("tableName cannot be blank");
    }

    @Test
    void testFlashbackQueryBlankTimestamp() {
        assertThatThrownBy(() -> databaseHealthTools.flashbackQuery("MY_TABLE", "", null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("timestamp cannot be blank");
    }

    @Test
    void testFlashbackQueryNullTimestamp() {
        assertThatThrownBy(() -> databaseHealthTools.flashbackQuery("MY_TABLE", null, null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("timestamp cannot be blank");
    }

    @Test
    void testShowUndoUsage() {
        Map<String, Object> result = databaseHealthTools.showUndoUsage("primary");
        assertThat(result).containsKey("dialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    // ─── P3: User and Privilege Audit ────────────────────────────────────────

    @Test
    void testListCurrentPrivileges() {
        Map<String, Object> result = databaseHealthTools.listCurrentPrivileges("primary");
        assertThat(result).containsKey("dialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    @Test
    void testListGrants() {
        Map<String, Object> result = databaseHealthTools.listGrants("TEST_USER", "primary");
        assertThat(result).containsKey("userName");
        assertThat(result.get("userName")).isEqualTo("TEST_USER");
        assertThat(result).containsKey("dialect");
        assertThat(result.get("rows")).isInstanceOf(List.class);
    }

    @Test
    void testListGrantsBlankUserName() {
        assertThatThrownBy(() -> databaseHealthTools.listGrants("", "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("userName cannot be blank");
    }

    @Test
    void testListGrantsNullUserName() {
        assertThatThrownBy(() -> databaseHealthTools.listGrants(null, "primary"))
                .isInstanceOf(McpToolException.class)
                .hasMessageContaining("userName cannot be blank");
    }
}
