/*
 * Copyright 2024-2026 Embabel Pty Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.entropy.database.mcp.audit;

import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Audit log repository for persisting query audit entries to database.
 *
 * <p>Registered only when {@code spring.datasource.url} is set. Without that key Boot still
 * auto-configures an anonymous embedded database when a driver like H2 is on the classpath, and
 * this repository used to bind to it — so audit rows landed in a throwaway in-memory schema that
 * disappeared on restart while {@code entropy.mcp.database.audit.enabled: true} reported
 * persistence as working. The condition is on the property rather than on the {@code JdbcTemplate}
 * bean because {@code @ConditionalOnBean} against an auto-configured bean is order-dependent for
 * scanned components, whereas property presence is not.
 *
 * <p>When the key is absent this bean is simply missing, and
 * {@code QueryAuditLoggerImpl}/{@code ComplianceReportService} take their documented
 * file-only paths — which is what the code always claimed happened.
 *
 * <p><b>方言：SQL 按数据库产品生成，不再假定 H2/PostgreSQL。</b>这个仓储拿到的是
 * {@code spring.datasource.url} 那条连接的 {@link JdbcTemplate}，不是 BYOK 连接，因此拿不到项目里的
 * {@code DatabaseDialect} 抽象；产品名改为通过 {@link DatabaseMetaData#getDatabaseProductName()} 探测一次
 * 并缓存（与建表的一次性初始化合并）。原来固定的一份 DDL/查询在非 H2、非 PostgreSQL 的库上必然失败：
 * {@code CREATE TABLE IF NOT EXISTS} 在 Oracle 与 SQL Server 不存在，
 * {@code GENERATED BY DEFAULT AS IDENTITY} 在 MySQL 不存在，{@code LIMIT ?} 在 Oracle 与 SQL Server 不存在。
 *
 * <p><b>破坏性变更（升级前必读）：列已改名</b> —— {@code sql} → {@code sql_text}、{@code rows} →
 * {@code row_count}、{@code timestamp} → {@code event_time}。原列名在 MySQL/Oracle 上是保留字或类型名
 * （{@code ROWS} 是 MySQL 8.0 保留字、{@code TIMESTAMP} 是类型名），不加引号无法解析；改名而不是加引号，
 * 是因为引号标识符会引入大小写敏感（Oracle 的 {@code "sql"} 与 {@code SQL} 是两个不同的列）。
 * <b>已经存在 {@code audit_log} 表的部署升级后会撞上「列不存在」</b>：本类只会在表不存在时建表，不会做迁移。
 * 需要保留历史数据的部署必须自行执行改名，例如：
 * <pre>
 * ALTER TABLE audit_log RENAME COLUMN sql TO sql_text;        -- MySQL 8.0 / PostgreSQL / Oracle
 * ALTER TABLE audit_log RENAME COLUMN rows TO row_count;
 * ALTER TABLE audit_log RENAME COLUMN timestamp TO event_time;
 * </pre>
 * 不需要历史数据的部署可以直接 {@code DROP TABLE audit_log}，本类会按当前产品重建。
 */
@Repository
@ConditionalOnProperty(name = "spring.datasource.url")
public class AuditLogRepository {

    private static final Logger log = LoggerFactory.getLogger(AuditLogRepository.class);

    private final JdbcTemplate jdbcTemplate;

    public AuditLogRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    private static final String CREATE_TABLE_SQL = """
            CREATE TABLE IF NOT EXISTS audit_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tool VARCHAR(100) NOT NULL,
                sql_text VARCHAR(2000),
                row_count INTEGER DEFAULT 0,
                duration_ms BIGINT DEFAULT 0,
                success INTEGER DEFAULT 1,
                error VARCHAR(1000),
                event_time TIMESTAMP NOT NULL,
                connection_key VARCHAR(200)
            )
            """;

    /**
     * MySQL 既不支持 {@code GENERATED BY DEFAULT AS IDENTITY}（自增只有 {@code AUTO_INCREMENT}），
     * 又把 {@code ROWS} 列为 8.0 保留字，所以这份 DDL 不能和 H2/PostgreSQL 共用。
     * {@code event_time} 用 {@code DATETIME(3)} 而不是 {@code TIMESTAMP}：MySQL 的 {@code TIMESTAMP}
     * 只能表示 1970–2038，且 {@code NOT NULL TIMESTAMP} 会被隐式加上「随行更新」的默认行为，审计时间被
     * 改写就失去了取证价值。
     */
    private static final String CREATE_TABLE_SQL_MYSQL = """
            CREATE TABLE IF NOT EXISTS audit_log (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                tool VARCHAR(100) NOT NULL,
                sql_text VARCHAR(2000),
                row_count INTEGER DEFAULT 0,
                duration_ms BIGINT DEFAULT 0,
                success INTEGER DEFAULT 1,
                error VARCHAR(1000),
                event_time DATETIME(3) NOT NULL,
                connection_key VARCHAR(200)
            )
            """;

    /**
     * Oracle 没有 {@code CREATE TABLE IF NOT EXISTS}（写了直接 ORA-00922 语法错误），所以这份 DDL 只能在
     * 确认表不存在时执行，见 {@link #ensureTableExists()}。类型也要落到 Oracle 自己的体系：
     * {@code VARCHAR} 虽然被接受但语义由 {@code VARCHAR2} 决定，{@code BIGINT}/{@code INTEGER} 在 Oracle
     * 里都会被折叠成 {@code NUMBER}，显式写出精度可以避免建出 {@code NUMBER(38)} 这种超宽列。
     */
    private static final String CREATE_TABLE_SQL_ORACLE = """
            CREATE TABLE audit_log (
                id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tool VARCHAR2(100) NOT NULL,
                sql_text VARCHAR2(2000),
                row_count NUMBER(10) DEFAULT 0,
                duration_ms NUMBER(19) DEFAULT 0,
                success NUMBER(1) DEFAULT 1,
                error VARCHAR2(1000),
                event_time TIMESTAMP NOT NULL,
                connection_key VARCHAR2(200)
            )
            """;

    /**
     * SQL Server 同样没有 {@code CREATE TABLE IF NOT EXISTS}，自增列的写法是 {@code IDENTITY(1,1)}；
     * {@code DATETIME2} 而不是 {@code TIMESTAMP}——SQL Server 的 {@code TIMESTAMP} 是行版本号（rowversion）
     * 的同义词，根本不是时间类型，用它建表会得到一个不能写入的二进制列。
     */
    private static final String CREATE_TABLE_SQL_SQLSERVER = """
            CREATE TABLE audit_log (
                id BIGINT IDENTITY(1,1) PRIMARY KEY,
                tool VARCHAR(100) NOT NULL,
                sql_text VARCHAR(2000),
                row_count INT DEFAULT 0,
                duration_ms BIGINT DEFAULT 0,
                success INT DEFAULT 1,
                error VARCHAR(1000),
                event_time DATETIME2 NOT NULL,
                connection_key VARCHAR(200)
            )
            """;

    /** 表名。存在性探测与 DDL 共用，避免两处写死后不同步。 */
    static final String TABLE_NAME = "audit_log";

    /**
     * 探测出的数据库产品族。只区分「DDL/分页写法不同」这一个维度，不是要复刻项目里的
     * {@code DatabaseDialect}：那套抽象绑在 BYOK 连接上，这个仓储拿不到。
     */
    enum Product {
        H2, POSTGRESQL, MYSQL, ORACLE, SQLSERVER, UNKNOWN
    }

    /**
     * 「表已存在」的厂商错误码。存在性探测和建表之间不是原子的（多实例同时启动、或者元数据被权限过滤掉
     * 导致探测漏判），此时建表会撞上「已存在」——这种失败必须放行，否则审计会在完全正常的表上永久报错。
     * 其余 DDL 失败（缺权限、表空间满）仍然要抛出来让人介入。
     */
    private static final Set<Integer> TABLE_ALREADY_EXISTS_CODES = Set.of(
            955,    // Oracle ORA-00955: name is already used by an existing object
            2714,   // SQL Server: There is already an object named 'audit_log'
            1050,   // MySQL ER_TABLE_EXISTS_ERROR
            42101   // H2: table already exists
    );

    /**
     * 建表只需要成功一次。这个类的实例是每个 BYOK 连接 new 一份的（见
     * {@code ByokDataSourceFactory}），拿不到 {@code @PostConstruct} 那种单例初始化语义，所以用
     * 实例级的 volatile 标记 + 双检：正常路径上每条审计都跑一次 {@code CREATE TABLE IF NOT EXISTS}
     * 是白付一次 DDL 往返，在 Oracle 这类会为 DDL 拿字典锁的库上尤其不划算。
     */
    private volatile boolean tableEnsured;

    /**
     * 探测到的产品族，与 {@link #tableEnsured} 一样只解析一次。产品探测本身要走一次连接拿元数据，
     * 每条审计都探一次和每条审计都建一次表是同一类浪费；{@code query()} 也需要它来选分页子句，所以缓存
     * 独立于建表标记（插入失败会重置 {@link #tableEnsured} 重新验表，但产品名不会因此改变）。
     */
    private volatile Product product;

    /**
     * Insert a new audit log entry.
     *
     * <p>Propagates the failure on purpose. Swallowing it here made
     * {@code QueryAuditLoggerImpl}'s circuit breaker unreachable, so a permanently unwritable
     * {@code audit_log} table produced one stack trace per query forever instead of degrading to
     * file-only auditing after the first failure.
     *
     * <p>建表失败与插入失败在异常消息里分开说明：前者通常是权限或方言问题（一次性、要人介入），
     * 后者可能只是连接池抖动（会被上层的半开熔断重试），运维要能从日志里直接区分。
     */
    public void insert(AuditLogEntity entity) {
        ensureTableExists();
        try {
            // 列名跟着建表一起改：sql/rows/timestamp 在 MySQL/Oracle 上是保留字或类型名，不加引号解析不过
            jdbcTemplate.update(
                "INSERT INTO audit_log (tool, sql_text, row_count, duration_ms, success, error, event_time, connection_key) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                entity.tool(),
                truncate(entity.sql(), 2000),
                entity.rows(),
                entity.durationMs(),
                entity.success(),
                truncate(entity.error(), 1000),
                entity.timestamp(),
                entity.connectionKey()
            );
        } catch (RuntimeException e) {
            // 插入失败可能只是表刚被删掉/重建，让下一次调用重新确认一次表结构
            this.tableEnsured = false;
            throw new IllegalStateException("Failed to insert into audit_log: " + e.getMessage(), e);
        }
    }

    /**
     * 确保 {@code audit_log} 存在，按探测到的数据库产品选择建表方式。
     *
     * <p>公开出来是为了让 {@code AuditLogInitializer} 复用同一份 DDL：它原先自己内联了一份写死的
     * H2/PostgreSQL 建表语句，启动时先把表按旧列名建出来，本类随后就只会看到「表已存在」而按新列名插入，
     * 结果是启动即坏。两处 DDL 必须同源。
     */
    public void ensureTableExists() {
        if (tableEnsured) {
            return;
        }
        synchronized (this) {
            if (tableEnsured) {
                return;
            }
            Product resolved = resolveProduct();
            try {
                if (supportsCreateTableIfNotExists(resolved)) {
                    jdbcTemplate.execute(createTableSql(resolved));
                } else if (!tableExists()) {
                    // Oracle / SQL Server 没有 IF NOT EXISTS，只能先查元数据再建
                    jdbcTemplate.execute(createTableSql(resolved));
                }
            } catch (RuntimeException e) {
                if (isTableAlreadyExists(e)) {
                    // 探测与建表之间不是原子的：表已经在了就当成功，不能让审计因为竞态永久失败
                    log.debug("audit_log already exists, treating the DDL failure as success: {}", e.getMessage());
                } else {
                    throw new IllegalStateException(
                            "Failed to create or verify the audit_log table (check DDL privileges and dialect): "
                                    + e.getMessage(), e);
                }
            }
            tableEnsured = true;
        }
    }

    /**
     * 探测一次数据库产品名并缓存。
     *
     * <p>探测失败不能让审计整体失败，所以退化成 {@link Product#UNKNOWN}，沿用原来的 H2/PostgreSQL 写法：
     * 那是这个仓储一直以来的行为，未识别的产品至少不会比现状更差。
     */
    private Product resolveProduct() {
        Product cached = this.product;
        if (cached != null) {
            return cached;
        }
        Product detected = Product.UNKNOWN;
        try {
            String productName = jdbcTemplate.execute(
                    (ConnectionCallback<String>) con -> con.getMetaData().getDatabaseProductName());
            detected = classify(productName);
        } catch (RuntimeException e) {
            log.warn("Could not detect the audit datasource product, falling back to standard SQL: {}",
                    e.getMessage());
        }
        this.product = detected;
        return detected;
    }

    /** 只按产品名做子串匹配：厂商版本号会变（"Oracle Database 19c"、"MySQL 8.4"），产品名不会。 */
    static Product classify(@Nullable String productName) {
        if (productName == null || productName.isBlank()) {
            return Product.UNKNOWN;
        }
        String name = productName.toLowerCase(Locale.ROOT);
        if (name.contains("h2")) {
            return Product.H2;
        }
        if (name.contains("postgres")) {
            return Product.POSTGRESQL;
        }
        // MariaDB 的 DDL/分页语法与 MySQL 同源，归到一起
        if (name.contains("mysql") || name.contains("mariadb")) {
            return Product.MYSQL;
        }
        if (name.contains("oracle")) {
            return Product.ORACLE;
        }
        if (name.contains("sql server")) {
            return Product.SQLSERVER;
        }
        return Product.UNKNOWN;
    }

    static String createTableSql(Product product) {
        return switch (product) {
            case MYSQL -> CREATE_TABLE_SQL_MYSQL;
            case ORACLE -> CREATE_TABLE_SQL_ORACLE;
            case SQLSERVER -> CREATE_TABLE_SQL_SQLSERVER;
            case H2, POSTGRESQL, UNKNOWN -> CREATE_TABLE_SQL;
        };
    }

    static boolean supportsCreateTableIfNotExists(Product product) {
        // Oracle 与 SQL Server 没有这个子句，写上去是语法错误而不是「忽略」
        return product != Product.ORACLE && product != Product.SQLSERVER;
    }

    /**
     * 分页子句。{@code LIMIT} 不是 SQL 标准：Oracle 12c 起只有 {@code FETCH FIRST n ROWS ONLY}，
     * SQL Server 只有 {@code TOP} 或 {@code OFFSET-FETCH}。这里取 {@code OFFSET-FETCH} 而不是 {@code TOP}，
     * 因为 {@code TOP} 要拼进 {@code SELECT} 之后，会把「按条件追加 WHERE」的拼接顺序打乱；
     * 两者都能吃占位符，而 {@code TOP (?)} 还要额外加括号。
     */
    static String limitClause(Product product) {
        return switch (product) {
            case ORACLE -> " FETCH FIRST ? ROWS ONLY";
            // SQL Server 的 FETCH NEXT 必须跟在 OFFSET 后面，不能单独出现
            case SQLSERVER -> " OFFSET 0 ROWS FETCH NEXT ? ROWS ONLY";
            case H2, POSTGRESQL, MYSQL, UNKNOWN -> " LIMIT ?";
        };
    }

    /**
     * 用 {@link DatabaseMetaData#getTables} 判断存在性，而不是 {@code SELECT ... FROM audit_log} 试错：
     * 后者在 Oracle 上会留下一条失败语句和一次硬解析，也无法区分「表不存在」与「没有 SELECT 权限」。
     *
     * <p>大小写要试两种：Oracle 与默认配置的 H2 把未加引号的标识符折叠成大写，PostgreSQL 折叠成小写。
     * 探测不出来（元数据被权限过滤、驱动返回 null）就当不存在，让后面的建表去撞「已存在」错误码。
     */
    private boolean tableExists() {
        Boolean exists = jdbcTemplate.execute((ConnectionCallback<Boolean>) con -> {
            DatabaseMetaData metaData = con.getMetaData();
            for (String candidate : new String[]{TABLE_NAME, TABLE_NAME.toUpperCase(Locale.ROOT)}) {
                try (ResultSet rs = metaData.getTables(null, null, candidate, new String[]{"TABLE"})) {
                    if (rs != null && rs.next()) {
                        return true;
                    }
                }
            }
            return false;
        });
        return Boolean.TRUE.equals(exists);
    }

    private static boolean isTableAlreadyExists(RuntimeException e) {
        Throwable cause = e;
        while (cause != null) {
            if (cause instanceof SQLException sqlException
                    && TABLE_ALREADY_EXISTS_CODES.contains(sqlException.getErrorCode())) {
                return true;
            }
            cause = cause.getCause();
        }
        return false;
    }


    /**
     * Query audit logs with optional filters.
     *
     * <p>分页子句按探测到的产品选择，见 {@link #limitClause(Product)}：写死的 {@code LIMIT ?} 在 Oracle 与
     * SQL Server 上是语法错误，审计历史查询在这两个库上从来就跑不通。
     */
    public List<AuditLogEntity> query(
            @Nullable String tool,
            @Nullable String connectionKey,
            @Nullable Instant startTime,
            @Nullable Instant endTime,
            int limit) {
        StringBuilder sql = new StringBuilder("SELECT id, tool, sql_text, row_count, duration_ms, success, error, event_time, connection_key FROM audit_log WHERE 1=1");
        var params = new ArrayList<>();

        if (tool != null && !tool.isBlank()) {
            sql.append(" AND tool = ?");
            params.add(tool);
        }
        if (connectionKey != null && !connectionKey.isBlank()) {
            sql.append(" AND connection_key = ?");
            params.add(connectionKey);
        }
        if (startTime != null) {
            sql.append(" AND event_time >= ?");
            params.add(startTime);
        }
        if (endTime != null) {
            sql.append(" AND event_time <= ?");
            params.add(endTime);
        }

        sql.append(" ORDER BY event_time DESC");
        sql.append(limitClause(resolveProduct()));
        params.add(limit);

        return jdbcTemplate.query(sql.toString(), params.toArray(), new AuditLogRowMapper());
    }

    /**
     * Delete audit logs older than the specified timestamp.
     */
    public int deleteOlderThan(Instant before) {
        try {
            return jdbcTemplate.update("DELETE FROM audit_log WHERE event_time < ?", before);
        } catch (Exception e) {
            log.warn("Failed to delete old audit logs", e);
            return 0;
        }
    }

    private static String truncate(String s, int max) {
        if (s == null) return null;
        return s.length() <= max ? s : s.substring(0, max);
    }

    private static class AuditLogRowMapper implements RowMapper<AuditLogEntity> {
        @Override
        public AuditLogEntity mapRow(ResultSet rs, int rowNum) throws SQLException {
            // 列名跟着建表改了；record 的字段名（sql/rows/timestamp）不变，改的只有物理列
            return new AuditLogEntity(
                rs.getLong("id"),
                rs.getString("tool"),
                rs.getString("sql_text"),
                rs.getInt("row_count"),
                rs.getLong("duration_ms"),
                rs.getBoolean("success"),
                rs.getString("error"),
                rs.getTimestamp("event_time").toInstant(),
                rs.getString("connection_key")
            );
        }
    }
}
