/*
 * Copyright 2024-2026 Embabel Pty Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.entropy.database.mcp.audit;

import org.junit.jupiter.api.Test;
import org.springframework.jdbc.BadSqlGrammarException;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * 建表语句与分页子句必须跟着数据库产品变。
 *
 * <p>原来两者都写死成 H2/PostgreSQL 语法：{@code CREATE TABLE IF NOT EXISTS} 在 Oracle/SQL Server 上是语法
 * 错误，{@code GENERATED BY DEFAULT AS IDENTITY} 在 MySQL 上不存在，{@code LIMIT ?} 在 Oracle/SQL Server 上
 * 也不存在——审计持久化在这三个库上根本不可用。这里用 stub 的 {@link DatabaseMetaData} 冒充各家产品，只断言
 * 与方言差异直接相关的片段。
 */
class AuditLogRepositoryDialectTest {

    private JdbcTemplate jdbcTemplate;
    private DatabaseMetaData metaData;
    private ResultSet tablesResultSet;

    private AuditLogRepository repositoryFor(String productName) throws SQLException {
        this.jdbcTemplate = mock(JdbcTemplate.class);
        this.metaData = mock(DatabaseMetaData.class);
        this.tablesResultSet = mock(ResultSet.class);
        Connection connection = mock(Connection.class);

        when(connection.getMetaData()).thenReturn(metaData);
        when(metaData.getDatabaseProductName()).thenReturn(productName);
        when(metaData.getTables(any(), any(), anyString(), any())).thenReturn(tablesResultSet);
        when(tablesResultSet.next()).thenReturn(false);

        // 产品探测与存在性探测都走 ConnectionCallback，交给 stub 的 Connection 执行
        when(jdbcTemplate.execute(any(ConnectionCallback.class)))
                .thenAnswer(invocation -> ((ConnectionCallback<?>) invocation.getArgument(0))
                        .doInConnection(connection));

        return new AuditLogRepository(jdbcTemplate);
    }

    private String capturedDdl() {
        var captor = org.mockito.ArgumentCaptor.forClass(String.class);
        verify(jdbcTemplate).execute(captor.capture());
        return captor.getValue();
    }

    @SuppressWarnings("unchecked")
    private String capturedQuerySql(AuditLogRepository repository) {
        when(jdbcTemplate.query(anyString(), any(Object[].class), any(RowMapper.class)))
                .thenReturn(List.of());
        repository.query(null, null, null, null, 10);
        var captor = org.mockito.ArgumentCaptor.forClass(String.class);
        verify(jdbcTemplate).query(captor.capture(), any(Object[].class), any(RowMapper.class));
        return captor.getValue();
    }

    @Test
    void mysqlGetsAutoIncrementInsteadOfIdentity() throws SQLException {
        AuditLogRepository repository = repositoryFor("MySQL");

        repository.ensureTableExists();

        String ddl = capturedDdl();
        assertThat(ddl).contains("AUTO_INCREMENT");
        assertThat(ddl).doesNotContain("GENERATED BY DEFAULT AS IDENTITY");
        // MySQL 支持 IF NOT EXISTS，不需要走元数据探测
        assertThat(ddl).contains("CREATE TABLE IF NOT EXISTS audit_log");
        assertThat(capturedQuerySql(repository)).endsWith(" LIMIT ?");
    }

    @Test
    void oracleGetsNoIfNotExistsAndFetchFirst() throws SQLException {
        AuditLogRepository repository = repositoryFor("Oracle");

        repository.ensureTableExists();

        String ddl = capturedDdl();
        assertThat(ddl).startsWith("CREATE TABLE audit_log");
        assertThat(ddl).doesNotContain("IF NOT EXISTS");
        assertThat(ddl).contains("VARCHAR2");
        assertThat(capturedQuerySql(repository)).endsWith(" FETCH FIRST ? ROWS ONLY");
    }

    @Test
    void sqlServerGetsIdentityColumnAndOffsetFetch() throws SQLException {
        AuditLogRepository repository = repositoryFor("Microsoft SQL Server");

        repository.ensureTableExists();

        String ddl = capturedDdl();
        assertThat(ddl).doesNotContain("IF NOT EXISTS");
        assertThat(ddl).contains("IDENTITY(1,1)");
        // TIMESTAMP 在 SQL Server 是行版本号而不是时间类型
        assertThat(ddl).contains("event_time DATETIME2");
        assertThat(capturedQuerySql(repository)).endsWith(" OFFSET 0 ROWS FETCH NEXT ? ROWS ONLY");
    }

    @Test
    void everyDialectUsesTheRenamedColumns() throws SQLException {
        for (String product : new String[]{"MySQL", "Oracle", "Microsoft SQL Server", "PostgreSQL", "H2"}) {
            AuditLogRepository repository = repositoryFor(product);
            repository.ensureTableExists();

            assertThat(capturedDdl())
                    .as("DDL for %s", product)
                    .contains("sql_text", "row_count", "event_time")
                    .doesNotContain(" sql ", " rows ", " timestamp ");
        }
    }

    @Test
    void skipsTheDdlWhenMetadataAlreadyReportsTheTable() throws SQLException {
        AuditLogRepository repository = repositoryFor("Oracle");
        when(tablesResultSet.next()).thenReturn(true);

        repository.ensureTableExists();

        // Oracle 上重复建表会报 ORA-00955，所以存在时必须完全不发 DDL
        verify(jdbcTemplate, never()).execute(anyString());
    }

    @Test
    void toleratesTableAlreadyExistsRaisedByTheDdl() throws SQLException {
        AuditLogRepository repository = repositoryFor("Oracle");
        // 探测说不存在、建表却撞上已存在：多实例并发启动或元数据被权限过滤时会这样，必须放行
        org.mockito.Mockito.doThrow(new BadSqlGrammarException(
                        "CREATE TABLE", "CREATE TABLE audit_log", new SQLException("ORA-00955", "42000", 955)))
                .when(jdbcTemplate).execute(anyString());

        assertThatCode(repository::ensureTableExists).doesNotThrowAnyException();
    }

    @Test
    void detectsTheProductOnlyOnce() throws SQLException {
        AuditLogRepository repository = repositoryFor("PostgreSQL");

        repository.ensureTableExists();
        repository.ensureTableExists();
        capturedQuerySql(repository);

        verify(metaData).getDatabaseProductName();
    }
}
